package com.sensorflow.backendcom.newrelic;

public enum ErrorTypes {
    CONCENTRATOR_ERROR,
    NODE_ERROR,
    NODE_EXCEPTION,
    SENSOR_ERROR,
    GATEWAY_ERROR,
    AUTOMATION_ENGINE_ERROR,
    CONFIGURATION_ERROR,
    NODE_CONNECTION_ERROR,
    MAPPING_ERROR,
    STREAMING_ERROR,
    OTA_ERROR,
    HASURA_ERROR,
    COMMAND_ERROR,
    MESSAGING_ERROR,
    BEACON_SPACE_FULL,
    NODE_IN_RECOVERY
}
